AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack of reports transactions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  TableReportTransactionsMonthlyName:
    Type: String
  TableReportTransactionsCategoryName:
    Type: String
  TableReportTransactionsCardName:
    Type: String
Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain

  ReportsTransactionsMonthlyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - sqs-monthly

  ReportsTransactionsCategoryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - sqs-category

  ReportsTransactionsCardQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - sqs-card
  
  ReportsTransactionsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sqs:*
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Resource: !GetAtt ReportsTransactionsMonthlyQueue.Arn
          - Action:
              - sqs:*
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Resource: !GetAtt ReportsTransactionsCardQueue.Arn
          - Action:
              - sqs:*
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Resource: !GetAtt ReportsTransactionsCategoryQueue.Arn
      Queues:
        - !Ref ReportsTransactionsMonthlyQueue
        - !Ref ReportsTransactionsCardQueue
        - !Ref ReportsTransactionsCategoryQueue

  SQSReportsTransactionMonthlyFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/sqsReportsTransactionsMonthly.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - monthly
      Environment:
        Variables:
          TABLE_NAME: !Ref TableReportTransactionsMonthlyName
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableReportTransactionsMonthlyName
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsMonthlyName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ReportsTransactionsMonthlyQueue.Arn

  SQSReportsTransactionCategoryFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/sqsReportsTransactionsCategory.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - category
      Environment:
        Variables:
          TABLE_NAME: !Ref TableReportTransactionsCategoryName
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableReportTransactionsCategoryName
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsCategoryName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ReportsTransactionsCategoryQueue.Arn
  
  SQSReportsTransactionCardFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/sqsReportsTransactionsCard.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - card
      Environment:
        Variables:
          TABLE_NAME: !Ref TableReportTransactionsCardName
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableReportTransactionsCardName
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsCardName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ReportsTransactionsCardQueue.Arn
  FindReportMonthlyTransactionFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/findReportMonthly.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - find-monthly
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsMonthlyName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableReportTransactionsMonthlyName

  # Logs
  SQSReportsCategoryTransactionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSReportsTransactionCategoryFunction}
      RetentionInDays: 14
  SQSReportsCardTransactionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSReportsTransactionCardFunction}
      RetentionInDays: 14
  SQSReportsMonthlyTransactionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSReportsTransactionMonthlyFunction}
      RetentionInDays: 14
  FindReportMonthlyTransactionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FindReportMonthlyTransactionFunction}
      RetentionInDays: 14
         