AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infra das lambdas
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  EnvName:
    Description: Nome do ambiente
    Type: String
    
Resources:
  LambdaServicesHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: LambdaServicesHttpApi
      StageName: dev

Outputs:
  ServerlessHttpApiId:
    Value: !Ref LambdaServicesHttpApi
    Export:
      Name: !Sub ${AWS::StackName}-ServerlessHttpApi
