AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API do Bot ifinancesBot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  TableUserBotPreferencesName:
    Type: String
  TableTransactionsCardName:
    Type: String
  TableTransactionsCategoryName:
    Type: String
  TableReportTransactionsMonthlyName:
    Type: String
  TableReportTransactionsCardName:
    Type: String
  Env:
    Type: String
  SecretTelegram:
    Type: String
  BusTransactionsName:
    Type: String
Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
  
  BotTelegramFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/processChat.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
      Environment:
        Variables:
          ENV: !Ref Env
          SECRET_TELEGRAM: !Ref SecretTelegram
          TABLE_TRANSACTIONS_CATEGORY_NAME: !Ref TableTransactionsCategoryName
          TABLE_USER_BOT_PREFERENCES_NAME: !Ref TableUserBotPreferencesName
          TABLE_TRANSACTIONS_CARD_NAME: !Ref TableTransactionsCardName
          TABLE_REPORT_TRANSACTIONS_MONTHLY_NAME: !Ref TableReportTransactionsMonthlyName
          TABLE_REPORT_TRANSACTIONS_CARD_NAME: !Ref TableReportTransactionsCardName
          BUS_TRANSACTIONS_NAME: !Ref BusTransactionsName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableUserBotPreferencesName
        - DynamoDBReadPolicy:
            TableName: !Ref TableTransactionsCardName
        - DynamoDBReadPolicy:
            TableName: !Ref TableTransactionsCategoryName
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsMonthlyName
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsCardName
        - SSMParameterReadPolicy: 
            ParameterName: '*'
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref BusTransactionsName
    
  SendMessageBotFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/sendMessageBot.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
          - send-message
      Environment:
        Variables:
          ENV: !Ref Env
          SECRET_TELEGRAM: !Ref SecretTelegram
      Policies:
        - SSMParameterReadPolicy: 
            ParameterName: '*'
      Events:
        Trigger:
          Type: EventBridgeRule 
          Properties:
            EventBusName: !Ref BusTransactionsName
            Pattern:
              source:
                - lambda.send-message

