AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API do Bot ifinancesBot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  TableUserBotPreferencesName:
    Type: String
  CreateTransactionsQueueName:
    Type: String
  TableTransactionsCardName:
    Type: String
  TableTransactionsCategoryName:
    Type: String
Globals:
  Function:
    Timeout: 10
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
  
  BotTelegramFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/processChat.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
      Environment:
        Variables:
          TABLE_TRANSACTIONS_CATEGORY_NAME: !Ref TableTransactionsCategoryName
          TABLE_USER_BOT_PREFERENCES_NAME: !Ref TableUserBotPreferencesName
          CREATE_TRANSACTION_QUEUE_NAME: !Ref CreateTransactionsQueueName
          TABLE_TRANSACTIONS_CARD_NAME: !Ref TableTransactionsCardName
      Policies:
        - DynamoDBReadPolicy:
          TableName: !Ref TableUserBotPreferencesName
        - DynamoDBReadPolicy:
          TableName: !Ref TableTransactionsCardName
        - DynamoDBReadPolicy:
          TableName: !Ref TableTransactionsCategoryName
        - SQSSendMessagePolicy:
          QueueName: !Ref CreateTransactionsQueueName
