export enum EventTypeEnum {
  SEND_QUEUE = 'SEND_QUEUE',
  ERROR_IN_SEND_QUEUE = 'ERROR_IN_SEND_QUEUE',
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_ERROR_IN_CREATED = 'TRANSACTION_ERROR_IN_CREATED',
}
