version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ifinances"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lgv2ub7g9rp"
s3_prefix = "ifinances"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
