AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack transactions category

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  TableReportTransactionsCategoryName:
    Type: String
Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
  
  FindTransactionsCategoryFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/find.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - find
      Environment:
        Variables:
          TABLE_NAME: !Ref TableReportTransactionsCategoryName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsCategoryName

  CreateTransactionsCategoryFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/create.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - create
      Environment:
        Variables:
          TABLE_NAME: !Ref TableReportTransactionsCategoryName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableReportTransactionsCategoryName
        - DynamoDBWritePolicy:
            TableName: !Ref TableReportTransactionsCategoryName


