AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de Users

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Runtime: nodejs18.x
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
  
  IFinancesUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ifinances-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  CreateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/create.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
        - - lambda
          - user-create
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref IFinancesUsersTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref IFinancesUsersTable
        
  FindUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/find.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
        - - lambda
          - user-find
      Architectures:
      - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref IFinancesUsersTable

  FindByIdUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/findById.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
          - lambda
          - user-find-by-id
      Architectures:
      - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref IFinancesUsersTable
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup


Outputs:
  FindUser:
    Description: "FindUser Lambda Function ARN"
    Value: !GetAtt FindUserFunction.Arn

  FindByIdUser:
    Description: "FindById Lambda Function ARN"
    Value: !GetAtt FindByIdUserFunction.Arn

  CreateUser:
    Description: "CreateUser Lambda Function ARN"
    Value: !GetAtt CreateUserFunction.Arn