AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  users

  Sample SAM Template for users

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  UsersGetByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: usersFunction/
      Handler: handler.getByUserId
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - handler.ts
      
  UsersApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Users API
          version: '1.0'
        paths:
          /users/{id}:
            get:
              parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    type: string
              responses:
                '200':
                  description: Successful response
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersGetByIdFunction.Arn}/invocations"
                credentials: !GetAtt [UserFunctionIamRole, Arn]
                type: aws_proxy
   
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/user/"
  UsersGetByIdFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt UsersGetByIdFunction.Arn
  UserFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt UserFunctionIamRole.Arn
