AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack of events

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  EventsTransactionsTableName:
    Type: String
Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain
  
  EventsTransactionsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - sqs-transactions
      FifoQueue: true

  EventsTransactionFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/eventsTransactions.handler
      FunctionName:
        Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - transactions
      Environment:
        Variables:
          EVENTS_TRANSACTIONS_TABLE_NAME: !Ref EventsTransactionsTableName
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref EventsTransactionsTableName
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTransactionsTableName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EventsTransactionsQueue.Arn
            BatchSize: 1

  EventsTransactionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${EventsTransactionFunction}
      RetentionInDays: 14