version = 0.1

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "cfstack-ifinances-prod-management-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v5lyb89zw0sl"
s3_prefix = "cfstack-ifinances-prod-management-data"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "cfstack-ifinances-dev-management-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v5lyb89zw0sl"
s3_prefix = "cfstack-ifinances-dev-management-data"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
