AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack management data ifinances

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  # TableTransactionsCardName:
  #   Type: String
  TransactionsTableName:
    Type: String
  TableTransactionsCategoryName:
    Type: String
 
Globals:
  Function:
    Timeout: 15
    Tracing: Active
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref RuntimeDependenciesLayer
  Api:
    TracingEnabled: true

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile 
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
  
  ImportDataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/importDataEvent.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
      Environment:
        Variables:
          TABLE_TRANSACTIONS_CATEGORY_NAME: !Ref TableTransactionsCategoryName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableTransactionsCategoryName
        - DynamoDBWritePolicy:
            TableName: !Ref TableTransactionsCategoryName

  ImportTransactionsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/importTransactions.handler
      FunctionName:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
          - transactions
      Environment:
        Variables:
          TRANSACTIONS_TABLE_NAME: !Ref TransactionsTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TransactionsTableName
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionsTableName
      
